language: ruby
rvm:
  - 2.1.5

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - pip install codecov

script:
  - bundle exec jekyll build
#  - bundle exec jekyll build --drafts
#  - bundle exec htmlproof ./_site

notifications:
  email: true

after_success:
  codecov
