- menu_name: "Services"

- name: "Search"
  url: "/search/"
  class: "services-contact"
  title: "Search"

- name: "Twitter"
  url: "https://twitter.com/roelverhaak"
  title: "Twitter"

- name: "RSS"
  url: "/feed.xml"
  class: "rss-link"
  title: "Subscribe to RSS"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  class: "sitemap-link"
  title: "Sitemap for Google Webmastertools"
